[package]
name = "Aufgabe5-Rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.dev]
opt-level = 3
overflow-checks = false

[profile.release]
opt-level = 3
overflow-checks = false